/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package DataContract.Item;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ItemDangerKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2016709311788805077L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ItemDangerKey\",\"namespace\":\"DataContract.Item\",\"fields\":[{\"name\":\"ID\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ItemDangerKey> ENCODER =
      new BinaryMessageEncoder<ItemDangerKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ItemDangerKey> DECODER =
      new BinaryMessageDecoder<ItemDangerKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ItemDangerKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ItemDangerKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ItemDangerKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ItemDangerKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ItemDangerKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ItemDangerKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ItemDangerKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ItemDangerKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int ID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ItemDangerKey() {}

  /**
   * All-args constructor.
   * @param ID The new value for ID
   */
  public ItemDangerKey(java.lang.Integer ID) {
    this.ID = ID;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ID = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ID' field.
   * @return The value of the 'ID' field.
   */
  public int getID() {
    return ID;
  }


  /**
   * Sets the value of the 'ID' field.
   * @param value the value to set.
   */
  public void setID(int value) {
    this.ID = value;
  }

  /**
   * Creates a new ItemDangerKey RecordBuilder.
   * @return A new ItemDangerKey RecordBuilder
   */
  public static DataContract.Item.ItemDangerKey.Builder newBuilder() {
    return new DataContract.Item.ItemDangerKey.Builder();
  }

  /**
   * Creates a new ItemDangerKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ItemDangerKey RecordBuilder
   */
  public static DataContract.Item.ItemDangerKey.Builder newBuilder(DataContract.Item.ItemDangerKey.Builder other) {
    if (other == null) {
      return new DataContract.Item.ItemDangerKey.Builder();
    } else {
      return new DataContract.Item.ItemDangerKey.Builder(other);
    }
  }

  /**
   * Creates a new ItemDangerKey RecordBuilder by copying an existing ItemDangerKey instance.
   * @param other The existing instance to copy.
   * @return A new ItemDangerKey RecordBuilder
   */
  public static DataContract.Item.ItemDangerKey.Builder newBuilder(DataContract.Item.ItemDangerKey other) {
    if (other == null) {
      return new DataContract.Item.ItemDangerKey.Builder();
    } else {
      return new DataContract.Item.ItemDangerKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for ItemDangerKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ItemDangerKey>
    implements org.apache.avro.data.RecordBuilder<ItemDangerKey> {

    private int ID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(DataContract.Item.ItemDangerKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing ItemDangerKey instance
     * @param other The existing instance to copy.
     */
    private Builder(DataContract.Item.ItemDangerKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'ID' field.
      * @return The value.
      */
    public int getID() {
      return ID;
    }


    /**
      * Sets the value of the 'ID' field.
      * @param value The value of 'ID'.
      * @return This builder.
      */
    public DataContract.Item.ItemDangerKey.Builder setID(int value) {
      validate(fields()[0], value);
      this.ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ID' field has been set.
      * @return True if the 'ID' field has been set, false otherwise.
      */
    public boolean hasID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ID' field.
      * @return This builder.
      */
    public DataContract.Item.ItemDangerKey.Builder clearID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ItemDangerKey build() {
      try {
        ItemDangerKey record = new ItemDangerKey();
        record.ID = fieldSetFlags()[0] ? this.ID : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ItemDangerKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<ItemDangerKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ItemDangerKey>
    READER$ = (org.apache.avro.io.DatumReader<ItemDangerKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.ID);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ID = in.readInt();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ID = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










