/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package DataContract.Item;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ItemType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3668637577489009452L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ItemType\",\"namespace\":\"DataContract.Item\",\"fields\":[{\"name\":\"ID\",\"type\":\"int\"},{\"name\":\"Description\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ItemType> ENCODER =
      new BinaryMessageEncoder<ItemType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ItemType> DECODER =
      new BinaryMessageDecoder<ItemType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ItemType> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ItemType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ItemType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ItemType>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ItemType to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ItemType from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ItemType instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ItemType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int ID;
  @Deprecated public java.lang.CharSequence Description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ItemType() {}

  /**
   * All-args constructor.
   * @param ID The new value for ID
   * @param Description The new value for Description
   */
  public ItemType(java.lang.Integer ID, java.lang.CharSequence Description) {
    this.ID = ID;
    this.Description = Description;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ID;
    case 1: return Description;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ID = (java.lang.Integer)value$; break;
    case 1: Description = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ID' field.
   * @return The value of the 'ID' field.
   */
  public int getID() {
    return ID;
  }


  /**
   * Sets the value of the 'ID' field.
   * @param value the value to set.
   */
  public void setID(int value) {
    this.ID = value;
  }

  /**
   * Gets the value of the 'Description' field.
   * @return The value of the 'Description' field.
   */
  public java.lang.CharSequence getDescription() {
    return Description;
  }


  /**
   * Sets the value of the 'Description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.Description = value;
  }

  /**
   * Creates a new ItemType RecordBuilder.
   * @return A new ItemType RecordBuilder
   */
  public static DataContract.Item.ItemType.Builder newBuilder() {
    return new DataContract.Item.ItemType.Builder();
  }

  /**
   * Creates a new ItemType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ItemType RecordBuilder
   */
  public static DataContract.Item.ItemType.Builder newBuilder(DataContract.Item.ItemType.Builder other) {
    if (other == null) {
      return new DataContract.Item.ItemType.Builder();
    } else {
      return new DataContract.Item.ItemType.Builder(other);
    }
  }

  /**
   * Creates a new ItemType RecordBuilder by copying an existing ItemType instance.
   * @param other The existing instance to copy.
   * @return A new ItemType RecordBuilder
   */
  public static DataContract.Item.ItemType.Builder newBuilder(DataContract.Item.ItemType other) {
    if (other == null) {
      return new DataContract.Item.ItemType.Builder();
    } else {
      return new DataContract.Item.ItemType.Builder(other);
    }
  }

  /**
   * RecordBuilder for ItemType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ItemType>
    implements org.apache.avro.data.RecordBuilder<ItemType> {

    private int ID;
    private java.lang.CharSequence Description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(DataContract.Item.ItemType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Description)) {
        this.Description = data().deepCopy(fields()[1].schema(), other.Description);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ItemType instance
     * @param other The existing instance to copy.
     */
    private Builder(DataContract.Item.ItemType other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Description)) {
        this.Description = data().deepCopy(fields()[1].schema(), other.Description);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'ID' field.
      * @return The value.
      */
    public int getID() {
      return ID;
    }


    /**
      * Sets the value of the 'ID' field.
      * @param value The value of 'ID'.
      * @return This builder.
      */
    public DataContract.Item.ItemType.Builder setID(int value) {
      validate(fields()[0], value);
      this.ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ID' field has been set.
      * @return True if the 'ID' field has been set, false otherwise.
      */
    public boolean hasID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ID' field.
      * @return This builder.
      */
    public DataContract.Item.ItemType.Builder clearID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return Description;
    }


    /**
      * Sets the value of the 'Description' field.
      * @param value The value of 'Description'.
      * @return This builder.
      */
    public DataContract.Item.ItemType.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Description' field has been set.
      * @return True if the 'Description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Description' field.
      * @return This builder.
      */
    public DataContract.Item.ItemType.Builder clearDescription() {
      Description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ItemType build() {
      try {
        ItemType record = new ItemType();
        record.ID = fieldSetFlags()[0] ? this.ID : (java.lang.Integer) defaultValue(fields()[0]);
        record.Description = fieldSetFlags()[1] ? this.Description : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ItemType>
    WRITER$ = (org.apache.avro.io.DatumWriter<ItemType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ItemType>
    READER$ = (org.apache.avro.io.DatumReader<ItemType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.ID);

    out.writeString(this.Description);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ID = in.readInt();

      this.Description = in.readString(this.Description instanceof Utf8 ? (Utf8)this.Description : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ID = in.readInt();
          break;

        case 1:
          this.Description = in.readString(this.Description instanceof Utf8 ? (Utf8)this.Description : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










